/*
 * Created on 28 juin 2013 ( Time 07:20:40 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */

package org.demo.persistence.services.jpa;

import org.demo.bean.Shop ;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.services.ShopPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Shop" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ShopPersistenceJPA extends GenericJpaService<Shop, String> implements ShopPersistence {

	/**
	 * Constructor
	 */
	public ShopPersistenceJPA() {
		super(Shop.class);
	}

	public Shop load( String code ) {
		return super.load( code );
	}

	public boolean delete( String code ) {
		return super.delete( code );
	}

	public boolean delete(Shop entity) {
		if ( entity != null ) {
			return super.delete( entity.getCode() );
		}
		return false ;
	}

}
