/*
 * JUnit test case for bean Author
 * Created on 25 juin 2013 ( Date ISO 2013-06-25 - Time 16:23:34 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */

package org.demo.test.mock;


import java.util.List;

import org.demo.bean.Author;
import org.demo.mock.AuthorMock;
import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Author persistence
 * 
 * @author Telosys Tools Generator
 *
 */
public class AuthorMockTest 
{
	@Test
	public void testMock() {
		
		System.out.println("Test Author mock..." );
		
		
		AuthorMock mock = new AuthorMock();
		
		Author instance = null ;
		instance = mock.createInstance() ;
		System.out.println("Author mock instance 1 : " );
		System.out.println(" . " + instance );
		Assert.assertNotNull(instance);
		
		instance = mock.createInstance(12) ;
		System.out.println("Author mock instance 2 : " );
		System.out.println(" . " + instance );
		Assert.assertNotNull(instance);
		Assert.assertTrue( instance.getId() == 12 );
		
		List<Author> list = mock.createList(10);
		Assert.assertNotNull(list);
		Assert.assertTrue( list.size() == 10 );
		System.out.println("Author mock list ( size = " + list.size() + " ) : " );
		for ( Author o : list ) {
			System.out.println(" . " + o );
		}
	}

}
