/*
 * Created on 28 juin 2013 ( Time 07:20:39 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.test.persistence;


import org.demo.bean.Author ;
import org.demo.mock.AuthorMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.AuthorPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Author persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AuthorPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Author persistence : delete + load ..." );
		
		AuthorPersistence service = PersistenceServiceProvider.getService(AuthorPersistence.class);
		
		AuthorMock mock = new AuthorMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(AuthorPersistence service, AuthorMock mock, int id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Author entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
