/*
 * Created on 2 juil. 2013 ( Time 09:44:49 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.test.persistence;


import org.demo.bean.Badge ;
import org.demo.mock.BadgeMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.BadgePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Badge persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class BadgePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Badge persistence : delete + load ..." );
		
		BadgePersistence service = PersistenceServiceProvider.getService(BadgePersistence.class);
		
		BadgeMock mock = new BadgeMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(BadgePersistence service, BadgeMock mock, int badgeNumber ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Badge entity = service.load( badgeNumber );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( badgeNumber ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( badgeNumber );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
