/*
 * JUnit test case for BookOrderItem persistence service
 * Created on 27 juin 2013 ( Time 17:47:56 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.test.persistence;


import org.demo.bean.BookOrderItem ;
import org.demo.mock.BookOrderItemMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.BookOrderItemPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for BookOrderItem persistence
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderItemPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test BookOrderItem persistence : delete + load ..." );
		
		BookOrderItemPersistence service = PersistenceServiceProvider.getService(BookOrderItemPersistence.class);
		
		BookOrderItemMock mock = new BookOrderItemMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(BookOrderItemPersistence service, BookOrderItemMock mock, int bookOrderId, int bookId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		BookOrderItem entity = service.load( bookOrderId, bookId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( bookOrderId, bookId ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . BookOrder
			// . Book
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( bookOrderId, bookId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
