/*
 * JUnit test case for BookOrder persistence service
 * Created on 27 juin 2013 ( Time 17:47:56 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.test.persistence;


import org.demo.bean.BookOrder ;
import org.demo.mock.BookOrderMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.BookOrderPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for BookOrder persistence
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test BookOrder persistence : delete + load ..." );
		
		BookOrderPersistence service = PersistenceServiceProvider.getService(BookOrderPersistence.class);
		
		BookOrderMock mock = new BookOrderMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(BookOrderPersistence service, BookOrderMock mock, int id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		BookOrder entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Shop
			// . Employee
			// . Customer
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
