/*
 * JUnit test case for Shop persistence service
 * Created on 27 juin 2013 ( Time 17:47:57 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.test.persistence;


import org.demo.bean.Shop ;
import org.demo.mock.ShopMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.ShopPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Shop persistence
 * 
 * @author Telosys Tools Generator
 *
 */
public class ShopPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Shop persistence : delete + load ..." );
		
		ShopPersistence service = PersistenceServiceProvider.getService(ShopPersistence.class);
		
		ShopMock mock = new ShopMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(ShopPersistence service, ShopMock mock, String code ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Shop entity = service.load( code );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( code ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Employee
			// . Country
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( code );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
