
/*
 * Created on 2 juil. 2013 ( Time 09:44:50 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.Shop ;
import org.demo.mock.tool.MockValues;

public class ShopMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Shop createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(3) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Shop createInstance( String code ) {
		Shop entity = new Shop();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setName( mockValues.nextString(80) ) ; // java.lang.String 
		entity.setAddress1( mockValues.nextString(80) ) ; // java.lang.String 
		entity.setAddress2( mockValues.nextString(80) ) ; // java.lang.String 
		entity.setZipCode( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setCity( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPhone( mockValues.nextString(14) ) ; // java.lang.String 
		entity.setEmail( mockValues.nextString(50) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setEmployee( TODO ) ; // Employee 
		// setListOfBookOrder( TODO ) ; // List<BookOrder> 
		// setCountry( TODO ) ; // Country 
		// setListOfEmployee( TODO ) ; // List<Employee> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Shop> createList(int count) {
		List<Shop> list = new LinkedList<Shop>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
