/*
 * Created on 2 juil. 2013 ( Date ISO 2013-07-02 - Time 09:44:50 )
 * Generated by Telosys Tools Generator ( version 2.0.5 )
 */
package org.demo.persistence.commons.jpa;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;

/**
 * JPA operation interface
 * Provided by Telosys Tools for JPA testing
 *
 */
public interface JpaOperation {

	/**
	 * Executes a JPA operation using the given EntityManager
	 * @param em the EntityManager to be used
	 * @return
	 * @throws PersistenceException
	 */
	public Object exectue(EntityManager em) throws PersistenceException;
	
}
